- hosts: localhost
  vars_files:
    vars.yaml
  tasks:

      # setup
    - name: make sure we're in the artifactory namespace
      command: >
        oc project devops-artifactory

      # patch primary
    - name: patch primary
      command: >
        oc process -f ./03a-artifactory-ha-primary.yaml --param-file=./{{env}}-artifactory-ha.env --ignore-unknown-parameters=true
      register: primary_processed
    - copy: content="{{ primary_processed.stdout }}" dest=./processed/03a-artifactory-ha-primary.json
    - name: apply 03a-artifactory-ha-primary
      command: >
        oc apply -f ./processed/03a-artifactory-ha-primary.json

    - pause:
        prompt: "Hit enter to continue once the primary patch has been completed"

      # patch secondary
    - name: patch member(s)
      command: >
        oc process -f ./03b-artifactory-ha-member.yaml --param-file=./{{env}}-artifactory-ha.env --ignore-unknown-parameters=true
      register: member_processed
    - copy: content="{{ member_processed.stdout }}" dest=./processed/03b-artifactory-ha-member.json
    - name: apply 03a-artifactory-ha-member
      command: >
        oc apply -f ./processed/03b-artifactory-ha-member.json
      when: env == 'prod'
